services:
    nti.payliance.customer:
        class: NTI\PaylianceBundle\Services\Customer\PLCustomerService
        arguments: ["@service_container"]
    nti.payliance.ach_account:
        class: NTI\PaylianceBundle\Services\ACH\PLACHAccountService
        arguments: ["@service_container"]
    nti.payliance.payment:
        class: NTI\PaylianceBundle\Services\Payment\PLPaymentService
        arguments: ["@service_container"]