services:
    payliance_api.customer:
        class: NTI\PaylianceBundle\Services\Customer\PLCustomerService
        arguments: ["@service_container"]
    payliance_api.ach_account:
        class: NTI\PaylianceBundle\Services\ACH\PLACHAccountService
        arguments: ["@service_container"]
    payliance_api.payment:
        class: NTI\PaylianceBundle\Services\Payment\PLPaymentService
        arguments: ["@service_container"]